repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
        args: ["--allow-multiple-documents"]
      - id: check-json
      - id: detect-private-key
      - id: check-added-large-files
        args: ["--maxkb=1024"]

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.9
    hooks:
      - id: bandit
        name: bandit (python security)
        args: ["-ll", "-ii"]
        files: ^(service|gateway|healthz)/.*\.py$

  - repo: local
    hooks:
      - id: hadolint
        name: hadolint (Dockerfile security)
        language: docker_image
        entry: hadolint/hadolint:latest
        files: (?i)(^|/)(Dockerfile|dockerfile)(\..*)?$
        pass_filenames: true

  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.18.4
    hooks:
      - id: gitleaks
        name: gitleaks (secrets scan)
        args: ["protect", "--staged", "--redact"]
