repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-json
      - id: detect-private-key
      - id: check-added-large-files
        args: ["--maxkb=1024"]

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.9
    hooks:
      - id: bandit
        name: bandit (python security)
        args: ["-r", "service", "gateway", "healthz", "-x", "frontend", "--severity-level", "medium", "--confidence-level", "medium"]

  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.18.4
    hooks:
      - id: gitleaks
        name: gitleaks (secrets scan)
        args: ["protect", "--staged", "--redact"]

  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
      - id: hadolint
        name: hadolint (Dockerfile security)
        files: '(?i)^(Dockerfile|.*/Dockerfile|dockerfile|Dockerfile\\..*)$'
