apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: service-discovery-ingress
  namespace: app
spec:
  ingressClassName: nginx
  rules:
    # localhost -> frontend (and gateway paths)
    - host: localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
          - path: /services
            pathType: Prefix
            backend:
              service:
                name: gateway
                port:
                  number: 8000
          - path: /healthz
            pathType: Prefix
            backend:
              service:
                name: gateway
                port:
                  number: 8000

    # consul.localhost -> consul UI
    - host: consul.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: consul
                port:
                  number: 8500
