apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-d
  namespace: service-discovery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-d
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: service-d
    spec:
      containers:
        - name: service-d
          image: s1natex/service-discovery:service-0.1.0
          imagePullPolicy: IfNotPresent
          env:
            - name: SERVICE_NAME
              value: service-d
            - name: SERVICE_PORT
              value: "5000"
            - name: CONSUL_HOST
              value: consul
            - name: CONSUL_PORT
              value: "8500"
          ports:
            - containerPort: 5000
          readinessProbe:
            httpGet:
              path: /info
              port: 5000
            initialDelaySeconds: 3
            periodSeconds: 5
            timeoutSeconds: 2
          livenessProbe:
            httpGet:
              path: /info
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2
---
apiVersion: v1
kind: Service
metadata:
  name: service-d
  namespace: service-discovery
spec:
  selector:
    app: service-d
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
  type: ClusterIP
