name: CI

on:
  push:
    branches:
      - '**'
    paths:
      - "frontend/**"
      - "gateway/**"
      - "service/**"
      - "healthz/**"
      - "tests/**"
      - ".github/workflows/ci.yml"

env:
  DOCKERHUB_REPO: s1natex/service-discovery
  FRONTEND_SVC: frontend
  GATEWAY_SVC: gateway
  SERVICE_SVC: service
  HEALTHZ_SVC: healthz

jobs:
  test-frontend:
    name: Frontend Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps
        working-directory: frontend
        run: |
          if [ -f package-lock.json ]; then npm ci; else npm i; fi

      - name: Run tests
        working-directory: frontend
        run: npm run test

  test-python:
    name: Python Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install pytest pytest-cov flask requests

      - name: Run tests
        run: pytest -q

  build-and-push:
    name: Build and Push Images
    runs-on: ubuntu-latest
    needs: [test-frontend, test-python]
    outputs:
      release_tag: ${{ steps.meta.outputs.release_tag }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Compute release tag (name-yyyymmdd-sha)
        id: meta
        run: |
          DATE=$(date -u +%Y%m%d)
          SHORT_SHA=${GITHUB_SHA::7}
          echo "release_tag=${DATE}-${SHORT_SHA}" >> "$GITHUB_OUTPUT"

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build images (cached) for final tags
        run: |
          docker build -t ${DOCKERHUB_REPO}:${FRONTEND_SVC}-${{ steps.meta.outputs.release_tag }} ./frontend
          docker build -t ${DOCKERHUB_REPO}:${GATEWAY_SVC}-${{ steps.meta.outputs.release_tag }}  ./gateway
          docker build -t ${DOCKERHUB_REPO}:${SERVICE_SVC}-${{ steps.meta.outputs.release_tag }}  ./service
          docker build -t ${DOCKERHUB_REPO}:${HEALTHZ_SVC}-${{ steps.meta.outputs.release_tag }}  ./healthz

      - name: Push images
        run: |
          docker push ${DOCKERHUB_REPO}:${FRONTEND_SVC}-${{ steps.meta.outputs.release_tag }}
          docker push ${DOCKERHUB_REPO}:${GATEWAY_SVC}-${{ steps.meta.outputs.release_tag }}
          docker push ${DOCKERHUB_REPO}:${SERVICE_SVC}-${{ steps.meta.outputs.release_tag }}
          docker push ${DOCKERHUB_REPO}:${HEALTHZ_SVC}-${{ steps.meta.outputs.release_tag }}

  update-manifests:
    name: Update K8s image tags and commit
    runs-on: ubuntu-latest
    needs: build-and-push
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Update K8s image tags
        env:
          RELEASE_TAG: ${{ needs.build-and-push.outputs.release_tag }}
          DOCKERHUB_REPO: s1natex/service-discovery
          FRONTEND_SVC: frontend
          GATEWAY_SVC: gateway
          SERVICE_SVC: service
          HEALTHZ_SVC: healthz
        run: |
          set -euo pipefail
          # manifests are under ./k8s/
          sed -i "s#${DOCKERHUB_REPO}:${FRONTEND_SVC}-[^[:space:]]\\+#${DOCKERHUB_REPO}:${FRONTEND_SVC}-${RELEASE_TAG}#g" k8s/frontend.yaml || true
          sed -i "s#${DOCKERHUB_REPO}:${GATEWAY_SVC}-[^[:space:]]\\+#${DOCKERHUB_REPO}:${GATEWAY_SVC}-${RELEASE_TAG}#g"  k8s/gateway.yaml  || true
          sed -i "s#${DOCKERHUB_REPO}:${HEALTHZ_SVC}-[^[:space:]]\\+#${DOCKERHUB_REPO}:${HEALTHZ_SVC}-${RELEASE_TAG}#g"  k8s/healthz.yaml  || true
          for f in k8s/service-a.yaml k8s/service-b.yaml k8s/service-c.yaml k8s/service-d.yaml; do
            sed -i "s#${DOCKERHUB_REPO}:${SERVICE_SVC}-[^[:space:]]\\+#${DOCKERHUB_REPO}:${SERVICE_SVC}-${RELEASE_TAG}#g" "$f" || true
          done
          git status --porcelain

      - name: Commit manifest changes [skip-ci]
        run: |
          if ! git diff --quiet; then
            git config user.name  "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add k8s/frontend.yaml k8s/gateway.yaml k8s/healthz.yaml k8s/service-*.yaml
            git commit -m "[skip-ci] Update image tags to ${RELEASE_TAG}"
            git push
          else
            echo "No manifest changes to commit."
          fi
