name: CI-CD

on:
  push:
    branches:
      - '**'
    paths:
      - "frontend/**"
      - "gateway/**"
      - "service/**"
      - "healthz/**"
      - "tests/**"
      - "docker-compose.ci.yml"
      - ".github/workflows/ci.yml"

env:
  DOCKERHUB_REPO: s1natex/service-discovery
  FRONTEND_SVC: frontend
  GATEWAY_SVC: gateway
  SERVICE_SVC: service
  HEALTHZ_SVC: healthz

jobs:
  test-frontend:
    name: Frontend Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install deps
        working-directory: frontend
        run: |
          if [ -f package-lock.json ]; then npm ci; else npm i; fi
      - name: Run tests
        working-directory: frontend
        run: npm run test

  test-python:
    name: Python Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install pytest pytest-cov flask requests
      - name: Run tests
        run: pytest -q

  build-and-push:
    name: Build and Push Images
    runs-on: ubuntu-latest
    needs: [test-frontend, test-python]
    env:
      DATE: ${{ github.event.repository.updated_at || '' }}
    steps:
      - uses: actions/checkout@v4

      - name: Compute release tag (name-yyyymmdd-sha)
        id: tag
        run: |
          set -euo pipefail
          DATE=$(date -u +%Y%m%d)
          SHORT_SHA=${GITHUB_SHA::7}
          echo "RELEASE_TAG=${DATE}-${SHORT_SHA}" >> "$GITHUB_ENV"

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build images (cached) for final tags
        run: |
          docker build -t ${DOCKERHUB_REPO}:${FRONTEND_SVC}-${RELEASE_TAG} ./frontend
          docker build -t ${DOCKERHUB_REPO}:${GATEWAY_SVC}-${RELEASE_TAG}  ./gateway
          docker build -t ${DOCKERHUB_REPO}:${SERVICE_SVC}-${RELEASE_TAG}  ./service
          docker build -t ${DOCKERHUB_REPO}:${HEALTHZ_SVC}-${RELEASE_TAG}  ./healthz

      - name: Push images
        run: |
          docker push ${DOCKERHUB_REPO}:${FRONTEND_SVC}-${RELEASE_TAG}
          docker push ${DOCKERHUB_REPO}:${GATEWAY_SVC}-${RELEASE_TAG}
          docker push ${DOCKERHUB_REPO}:${SERVICE_SVC}-${RELEASE_TAG}
          docker push ${DOCKERHUB_REPO}:${HEALTHZ_SVC}-${RELEASE_TAG}

  update-manifests:
    name: Update K8s image tags and commit
    runs-on: ubuntu-latest
    needs: build-and-push
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Update K8s image tags
        env:
          RELEASE_TAG: ${{ env.RELEASE_TAG }}
        run: |
          set -euo pipefail
          # Example: single aggregated manifest file
          if [ -f k8s/apps/deployments.yaml ]; then
            sed -i "s#${DOCKERHUB_REPO}:frontend-[^[:space:]]\\+#${DOCKERHUB_REPO}:${FRONTEND_SVC}-${RELEASE_TAG}#g" k8s/apps/deployments.yaml
            sed -i "s#${DOCKERHUB_REPO}:gateway-[^[:space:]]\\+#${DOCKERHUB_REPO}:${GATEWAY_SVC}-${RELEASE_TAG}#g"   k8s/apps/deployments.yaml
            sed -i "s#${DOCKERHUB_REPO}:service-[^[:space:]]\\+#${DOCKERHUB_REPO}:${SERVICE_SVC}-${RELEASE_TAG}#g"   k8s/apps/deployments.yaml
            sed -i "s#${DOCKERHUB_REPO}:healthz-[^[:space:]]\\+#${DOCKERHUB_REPO}:${HEALTHZ_SVC}-${RELEASE_TAG}#g"   k8s/apps/deployments.yaml
          fi

          # If manifests are split per service (uncomment and adjust paths):
          # sed -i "s#${DOCKERHUB_REPO}:frontend-[^[:space:]]\\+#${DOCKERHUB_REPO}:${FRONTEND_SVC}-${RELEASE_TAG}#g" frontend.yaml || true
          # sed -i "s#${DOCKERHUB_REPO}:gateway-[^[:space:]]\\+#${DOCKERHUB_REPO}:${GATEWAY_SVC}-${RELEASE_TAG}#g"  gateway.yaml  || true
          # sed -i "s#${DOCKERHUB_REPO}:healthz-[^[:space:]]\\+#${DOCKERHUB_REPO}:${HEALTHZ_SVC}-${RELEASE_TAG}#g"  healthz.yaml  || true
          # for f in service-a.yaml service-b.yaml service-c.yaml service-d.yaml; do
          #   sed -i "s#${DOCKERHUB_REPO}:service-[^[:space:]]\\+#${DOCKERHUB_REPO}:${SERVICE_SVC}-${RELEASE_TAG}#g" "$f" || true
          # done

          git status --porcelain

      - name: Commit manifest changes [skip-ci]
        if: ${{ !cancelled() }}
        run: |
          if ! git diff --quiet; then
            git config user.name  "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            # Commit whichever files changed:
            if [ -f k8s/apps/deployments.yaml ]; then
              git add k8s/apps/deployments.yaml
            fi
            # git add frontend.yaml gateway.yaml healthz.yaml service-*.yaml || true
            git commit -m "[skip-ci] Update image tags to ${RELEASE_TAG}"
            git push
          else
            echo "No manifest changes to commit."
          fi
